# Generated by Django 5.2.9 on 2025-12-04 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_desembolso', models.DateField()),
                ('tea_anual', models.DecimalField(decimal_places=4, max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('frecuencia_nombre', models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral')], max_length=20)),
                ('dias_periodo', models.IntegerField(default=0, editable=False)),
                ('tasa_periodo', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=10)),
                ('total_cuotas', models.IntegerField(default=0, editable=False)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_doc', models.CharField(default='DNI', max_length=20)),
                ('nro_doc', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('tipo_servicio', models.CharField(help_text='Ej: Construcción, Legal, Marketing', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Planos', 'En Planos'), ('Preventa', 'En Preventa'), ('Construccion', 'En Construcción'), ('Entregado', 'Entregado')], default='Planos', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('total_unidades', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_ventas_banco', models.IntegerField(default=0, editable=False, help_text='Calculado automáticamente (30% del total)')),
                ('banco_activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.IntegerField()),
                ('fecha_programada', models.DateField()),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('es_ultima_cuota', models.BooleanField(default=False)),
                ('saldo_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amortizacion_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.inversion')),
            ],
        ),
        migrations.AddField(
            model_name='inversion',
            name='inversor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inversor'),
        ),
        migrations.CreateModel(
            name='ProveedorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='inversion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('Directo', 'Gasto Directo'), ('Indirecto', 'Gasto Indirecto')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_gasto', models.DateField()),
                ('nro_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('url_comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(default='Pagado', max_length=50)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('url_archivo', models.URLField(help_text='Link a Google Drive / Dropbox')),
                ('estado', models.CharField(default='Vigente', max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_interes', models.DateField(auto_now_add=True)),
                ('estado_interes', models.CharField(default='Seguimiento', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('plano_modelo', models.URLField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Separado', 'Separado'), ('Vendido', 'Vendido')], default='Disponible', max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodepartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_financiamiento', models.CharField(max_length=50)),
                ('entidad_financiera', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_financiado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
            ],
        ),
    ]
