# Generated by Django 5.2.9 on 2025-12-31 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.IntegerField()),
                ('fecha_programada', models.DateField()),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('dias_periodo', models.IntegerField(default=0)),
                ('saldo_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interes_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amortizacion_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_ultima_cuota', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', '$ (Dólares)')], default='PEN', max_length=3)),
                ('capital_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_desembolso', models.DateField()),
                ('tea_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('frecuencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral')], max_length=20)),
                ('estado', models.CharField(default='Activo', editable=False, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Inversiones',
            },
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI - Persona'), ('RUC', 'RUC - Empresa')], default='DNI', max_length=10)),
                ('nro_doc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Inversores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Planos', 'En Planos'), ('Preventa', 'En Preventa'), ('Construccion', 'En Construcción'), ('Entregado', 'Entregado')], default='Planos', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('total_unidades', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_ventas_banco', models.IntegerField(default=0, editable=False)),
                ('banco_activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPagos',
            fields=[
            ],
            options={
                'verbose_name': 'Calendario de Pagos',
                'verbose_name_plural': 'Calendario de Pagos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cuotainversion',),
        ),
        migrations.AddField(
            model_name='cuotainversion',
            name='inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.inversion'),
        ),
        migrations.AddField(
            model_name='inversion',
            name='inversor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inversor'),
        ),
        migrations.CreateModel(
            name='ProveedorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('moneda', models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', '$ (Dólares)')], default='PEN', max_length=3)),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='inversion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('Directo', 'Gasto Directo'), ('Indirecto', 'Gasto Indirecto')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('moneda', models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', '$ (Dólares)')], default='PEN', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_gasto', models.DateField()),
                ('nro_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gasto_comprobantes/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pagado', max_length=20)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_proyecto/')),
                ('estado', models.CharField(default='Vigente', max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_interes', models.DateField(auto_now_add=True)),
                ('estado_interes', models.CharField(choices=[('Seguimiento', 'En Seguimiento'), ('Negociacion', 'En Negociación'), ('Comprado', 'VENTA CERRADA'), ('Caido', 'Venta Caída')], default='Seguimiento', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Interés / Lead',
                'verbose_name_plural': 'Intereses / Leads',
            },
        ),
        migrations.CreateModel(
            name='TipoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plano_modelo', models.FileField(blank=True, null=True, upload_to='planos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(max_length=20)),
                ('piso', models.IntegerField(default=1)),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Separado', 'Separado'), ('Vendido', 'Vendido')], default='Disponible', max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodepartamento')),
            ],
            options={
                'unique_together': {('tipo', 'nro')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('moneda', models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', '$ (Dólares)')], default='PEN', max_length=3)),
                ('precio_lista', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('tipo_financiamiento', models.CharField(choices=[('Hipotecario', 'Crédito Hipotecario'), ('Directo', 'Crédito Directo'), ('Contado', 'Al Contado')], default='Hipotecario', max_length=20)),
                ('entidad_financiera', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_financiado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
            ],
        ),
    ]
