# Generated by Django 5.2.9 on 2026-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendapagos',
            options={'verbose_name': 'Agenda de Pagos', 'verbose_name_plural': 'Agenda de Pagos (Pendientes)'},
        ),
        migrations.AlterModelOptions(
            name='cuotainversion',
            options={'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='inversion',
            name='tipo_calculo',
            field=models.CharField(choices=[('FINANCIERO', 'Financiero (Días exactos - Monto Variable)'), ('COMERCIAL', 'Comercial (360 días - Monto Fijo)')], default='FINANCIERO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inversor',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10),
        ),
    ]
