# Generated by Django 5.2.9 on 2026-01-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agendapagos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendapagos',
            options={'verbose_name': 'Agenda de Pagos', 'verbose_name_plural': 'Agenda de Pagos'},
        ),
    ]
