# Generated by Django 5.2.9 on 2026-02-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agendapagos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='banco',
            field=models.CharField(blank=True, choices=[('BCP', 'Banco de Crédito del Perú (BCP)'), ('BBVA', 'BBVA Continental'), ('INTERBANK', 'Interbank'), ('SCOTIABANK', 'Scotiabank'), ('BANBIF', 'BanBif'), ('PICHINCHA', 'Banco Pichincha'), ('NACION', 'Banco de la Nación'), ('CAJA_AREQUIPA', 'Caja Arequipa'), ('OTRO', 'Otro...')], max_length=50, null=True, verbose_name='Banco de Abono'),
        ),
        migrations.AddField(
            model_name='inversor',
            name='cci',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Cuenta Interbancario (CCI)'),
        ),
        migrations.AddField(
            model_name='inversor',
            name='cuenta_abono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
    ]
