# Generated by Django 5.2.9 on 2026-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inversor_banco_inversor_cci_inversor_cuenta_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='tipo_calculo',
            field=models.CharField(choices=[('FINANCIERO', 'Financiero (Días exactos - Monto Variable)'), ('COMERCIAL', 'Comercial (360 días - Monto Fijo)'), ('MANUAL', 'Manual (Personalizado)')], default='FINANCIERO', max_length=20),
        ),
    ]
