# Generated by Django 5.2.9 on 2026-02-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inversion_tipo_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='banco_personalizado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar Otro Banco'),
        ),
    ]
