# Generated by Django 5.2.9 on 2026-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inversor_banco_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='destino_fondos',
            field=models.TextField(blank=True, help_text='Ej: $80k para Casa Porta, $20k para remodelación de oficinas Casa 18.', null=True, verbose_name='Destino de los Fondos / Descripción'),
        ),
        migrations.AddField(
            model_name='inversion',
            name='responsable_pago',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto (Costo del proyecto)'), ('CASA18', 'Casa 18 (Gasto corporativo)'), ('COMPARTIDO', 'Compartido (Múltiples destinos)')], default='PROYECTO', max_length=20, verbose_name='Responsable de los Intereses'),
        ),
    ]
