# Generated by Django 5.2.9 on 2026-02-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inversion_destino_fondos_inversion_responsable_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='plazo_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='responsable_pago',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto'), ('CASA18', 'Casa 18 (Gasto corporativo)'), ('COMPARTIDO', 'Compartido (Múltiples destinos)')], default='PROYECTO', max_length=20, verbose_name='Responsable de los Intereses'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='tea_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='tipo_calculo',
            field=models.CharField(choices=[('FINANCIERO', 'Financiero (Días exactos - Monto Variable)'), ('COMERCIAL', 'Comercial (360 días - Monto Fijo)'), ('MANUAL', 'Manual (Personalizado)'), ('EQUITY', 'Socio / Capital a Riesgo (Equity)')], default='FINANCIERO', max_length=20),
        ),
    ]
