# Generated by Django 5.2.9 on 2026-02-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_inversion_plazo_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='plazo_meses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inversion',
            name='tea_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
