# Generated by Django 5.2.9 on 2026-02-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inversion_plazo_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_prestatario',
            field=models.BooleanField(default=False, verbose_name='Es Prestatario (Préstamos)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_prospecto_inmobiliario',
            field=models.BooleanField(default=True, verbose_name='Es Lead/Prospecto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nro_documento',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Nro. Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'CE'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre / Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteproyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_proyectos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_inmobiliarias', to='core.cliente'),
        ),
        migrations.CreateModel(
            name='PrestamoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_prestamo', models.CharField(help_text='Ej: Préstamo personal, compra de auto', max_length=255, verbose_name='Motivo / Concepto')),
                ('moneda', models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', '$ (Dólares)')], default='PEN', max_length=3)),
                ('capital_monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Prestado')),
                ('fecha_desembolso', models.DateField(verbose_name='Fecha de entrega del dinero')),
                ('tea_anual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TEA (%)')),
                ('plazo_meses', models.IntegerField(verbose_name='Plazo (Meses)')),
                ('frecuencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral')], default='Mensual', max_length=20)),
                ('tipo_calculo', models.CharField(choices=[('FINANCIERO', 'Financiero (Días exactos)'), ('COMERCIAL', 'Comercial (360 días)'), ('MANUAL', 'Manual (Personalizado)')], default='FINANCIERO', max_length=20)),
                ('estado', models.CharField(default='Activo', editable=False, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_recibidos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Préstamo a Tercero',
                'verbose_name_plural': 'Préstamos a Terceros',
            },
        ),
        migrations.CreateModel(
            name='CuotaPrestamoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.IntegerField()),
                ('fecha_programada', models.DateField()),
                ('dias_periodo', models.IntegerField(default=30)),
                ('saldo_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amortizacion_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_ultima_cuota', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamotercero')),
            ],
            options={
                'verbose_name': 'Cuota de Cobro',
                'verbose_name_plural': 'Cuotas de Cobro',
                'ordering': ['nro_cuota'],
            },
        ),
    ]
