# Generated by Django 5.2.9 on 2026-02-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_direccion_cliente_es_prestatario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Archivo / Documento', 'verbose_name_plural': 'Archivos / Documentos'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='documento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ej: Voucher de transferencia - Cuota 1', max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.inversion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.prestamotercero'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='casa18/documentos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('PLANO', 'Plano de Departamento'), ('COMPROBANTE', 'Comprobante de Pago (Voucher)'), ('RETENCION', 'Certificado de Retención'), ('CONTRATO', 'Contrato / Documento Legal'), ('OTROS', 'Otros')], max_length=20),
        ),
    ]
