# Generated by Django 5.2.9 on 2026-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_documento_options_remove_documento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('INMOBILIARIO', 'Proyecto Inmobiliario (Edificio)'), ('OPERATIVO', 'Fondo Empresarial / Operativo')], default='INMOBILIARIO', max_length=20),
        ),
    ]
