# Generated by Django 5.2.9 on 2026-02-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('INMOBILIARIO', 'Edificio'), ('EMPRESARIAL', 'Casa18')], default='INMOBILIARIO', max_length=20),
        ),
    ]
