# Generated by Django 5.2.9 on 2026-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_proyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Planos', 'Planos'), ('En Construcción', 'En Construcción'), ('Finalizado', 'Finalizado'), ('Operativo', 'Operativo')], default='Planos', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
