# Generated by Django 5.2.9 on 2026-02-25 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_proyecto_estado_alter_proyecto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tipodepartamento',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Planos', 'En Planos'), ('En Construcción', 'En Construcción'), ('En Preventa', 'En Preventa'), ('Finalizado', 'Finalizado'), ('Operativo', 'Operativo')], default='Planos', max_length=50),
        ),
        migrations.CreateModel(
            name='UnidadInmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('COCHERA', 'Cochera'), ('DEPOSITO', 'Depósito')], default='DEPARTAMENTO', max_length=20)),
                ('numero', models.CharField(max_length=50, verbose_name='Número o Identificador')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m2)')),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Separado', 'Separado'), ('Vendido', 'Vendido')], default='Disponible', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Unidad Inmobiliaria',
                'verbose_name_plural': 'Unidades Inmobiliarias',
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.unidadinmobiliaria'),
        ),
        migrations.AddField(
            model_name='venta',
            name='unidad',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.unidadinmobiliaria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='TipoDepartamento',
        ),
    ]
