# Generated by Django 5.2.9 on 2026-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_venta_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='area_vendible_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Construida Total (m²)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingreso_proyectado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingreso Proyectado'),
        ),
    ]
