# Generated by Django 5.2.9 on 2026-03-12 23:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_proyecto_area_vendible_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotainversion',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=core.models.ruta_comprobante),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='casa18/gastos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='responsable_pago',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto'), ('CASA18', 'Casa 18 (Gasto corporativo)'), ('COMPARTIDO', 'Compartido (Múltiples destinos)')], default='PROYECTO', max_length=20, verbose_name='responsable'),
        ),
    ]
