# Generated by Django 5.2.9 on 2026-03-14 18:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cuotainversion_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotainversion',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to=core.models.ruta_factura, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='cuotainversion',
            name='retencion',
            field=models.FileField(blank=True, null=True, upload_to=core.models.ruta_retencion, verbose_name='Retención Impuesto a la Renta'),
        ),
        migrations.AlterField(
            model_name='cuotainversion',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=core.models.ruta_comprobante, verbose_name='Comprobante'),
        ),
    ]
