# Generated by Django 5.2.9 on 2026-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cuotainversion_factura_cuotainversion_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotainversion',
            name='comprobante_log',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuotainversion',
            name='factura_log',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuotainversion',
            name='retencion_log',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
