# Generated by Django 5.2.9 on 2026-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cuotainversion_comprobante_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotainversion',
            name='estado_log',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
